DWARF_ATTR(DW_AT_sibling, 0x01)
DWARF_ATTR(DW_AT_location , 0x02)
DWARF_ATTR(DW_AT_name , 0x03)
DWARF_ATTR(DW_AT_ordering , 0x09)
DWARF_ATTR(DW_AT_byte_size , 0x0b)
DWARF_ATTR(DW_AT_bit_offset , 0x0c)
DWARF_ATTR(DW_AT_bit_size, 0x0d)
DWARF_ATTR(DW_AT_stmt_list , 0x10)
DWARF_ATTR(DW_AT_low_pc , 0x11)
DWARF_ATTR(DW_AT_high_pc , 0x12)
DWARF_ATTR(DW_AT_language , 0x13)
DWARF_ATTR(DW_AT_discr, 0x15)
DWARF_ATTR(DW_AT_discr_value, 0x16)
DWARF_ATTR(DW_AT_visibility, 0x17)
DWARF_ATTR(DW_AT_import, 0x18)
DWARF_ATTR(DW_AT_string_length, 0x19)
DWARF_ATTR(DW_AT_common_reference, 0x1a)
DWARF_ATTR(DW_AT_comp_dir, 0x1b)
DWARF_ATTR(DW_AT_const_value, 0x1c)
DWARF_ATTR(DW_AT_containing_type, 0x1d)
DWARF_ATTR(DW_AT_default_value, 0x1e)
DWARF_ATTR(DW_AT_inline, 0x20)
DWARF_ATTR(DW_AT_is_optional, 0x21)
DWARF_ATTR(DW_AT_lower_bound, 0x22)
DWARF_ATTR(DW_AT_producer, 0x25)
DWARF_ATTR(DW_AT_prototyped, 0x27)
DWARF_ATTR(DW_AT_return_addr, 0x2a)
DWARF_ATTR(DW_AT_start_scope, 0x2c)
DWARF_ATTR(DW_AT_stride_size, 0x2e)
DWARF_ATTR(DW_AT_upper_bound, 0x2f)
DWARF_ATTR(DW_AT_abstract_origin, 0x31)
DWARF_ATTR(DW_AT_accessibility, 0x32)
DWARF_ATTR(DW_AT_address_class, 0x33)
DWARF_ATTR(DW_AT_artificial, 0x34)
DWARF_ATTR(DW_AT_base_types, 0x35)
DWARF_ATTR(DW_AT_calling_convention, 0x36)
DWARF_ATTR(DW_AT_count, 0x37)
DWARF_ATTR(DW_AT_data_member_location, 0x38)
DWARF_ATTR(DW_AT_decl_column, 0x39)
DWARF_ATTR(DW_AT_decl_file, 0x3a)
DWARF_ATTR(DW_AT_decl_line, 0x3b)
DWARF_ATTR(DW_AT_declaration, 0x3c)
DWARF_ATTR(DW_AT_discr_list, 0x3d)
DWARF_ATTR(DW_AT_encoding, 0x3e)
DWARF_ATTR(DW_AT_external, 0x3f)
DWARF_ATTR(DW_AT_frame_base, 0x40)
DWARF_ATTR(DW_AT_friend, 0x41)
DWARF_ATTR(DW_AT_identifier_case, 0x42)
DWARF_ATTR(DW_AT_macro_info, 0x43)
DWARF_ATTR(DW_AT_namelist_item, 0x44)
DWARF_ATTR(DW_AT_priority, 0x45)
DWARF_ATTR(DW_AT_segment, 0x46)
DWARF_ATTR(DW_AT_specification, 0x47)
DWARF_ATTR(DW_AT_static_link, 0x48)
DWARF_ATTR(DW_AT_type, 0x49)
DWARF_ATTR(DW_AT_use_location, 0x4a)
DWARF_ATTR(DW_AT_variable_parameter, 0x4b)
DWARF_ATTR(DW_AT_virtuality, 0x4c)
DWARF_ATTR(DW_AT_vtable_elem_location, 0x4d)
DWARF_ATTR(DW_AT_allocated, 0x4e)
DWARF_ATTR(DW_AT_associated, 0x4f)
DWARF_ATTR(DW_AT_data_location, 0x50)
DWARF_ATTR(DW_AT_byte_stride, 0x51)
DWARF_ATTR(DW_AT_entry_pc, 0x52)
DWARF_ATTR(DW_AT_use_UTF8, 0x53)
DWARF_ATTR(DW_AT_extension, 0x54)
DWARF_ATTR(DW_AT_ranges, 0x55)
DWARF_ATTR(DW_AT_trampoline, 0x56)
DWARF_ATTR(DW_AT_call_column, 0x57)
DWARF_ATTR(DW_AT_call_file, 0x58)
DWARF_ATTR(DW_AT_linkage_name, 0x6E)

DWARF_ATTR(DW_AT_lo_user, 0x2000)
DWARF_ATTR(DW_AT_hi_user, 0x3fff)
