name: C/C++ CI

on:
  push:
    branches: [ "master", "v2.12-maint" ]
  pull_request:
    branches: [ "master", "v2.12-maint" ]

jobs:
  build-gcc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        sudo apt install g++ liblzma-dev zlib1g-dev
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++
    - name: make
      run: make VERBOSE=1
    - name: make check
      run: make check CTEST_OUTPUT_ON_FAILURE=TRUE

  build-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        sudo apt install clang liblzma-dev zlib1g-dev
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
    - name: make
      run: make VERBOSE=1
    - name: make check
      run: make check CTEST_OUTPUT_ON_FAILURE=TRUE
